name: BuildAndUploadPackage

on:
  push:
    branches: '*/stable/*'

jobs:
  Win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install and configure Conan
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        run: |
          python -m pip install conan
          conan remote add vectrom https://artifactory.plociennik.net/artifactory/api/conan/conan
          conan user -p "$env:ARTIFACTORY_API_KEY" -r vectrom github

      - name: Create packages
        run: |
          apt-get install -y libgl1-mesa-dev
          conan create . qt/5.15.0@vectrom/stable -s build_type=Release -o qt:qttools=True
          conan create . qt/5.15.0@vectrom/stable -s build_type=Debug -o qt:qttools=True

      - name: Upload
        run: conan upload qt/5.15.0@vectrom/stable -r vectrom --all

  Lnx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install and configure Conan
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        run: |
          python -m pip install conan
          conan remote add vectrom https://artifactory.plociennik.net/artifactory/api/conan/conan
          conan user -p "$ARTIFACTORY_API_KEY" -r vectrom github

      - name: Create packages
        run: |
          conan create . qt/5.15.0@vectrom/stable -s build_type=Release -o qt:qttools=True
          conan create . qt/5.15.0@vectrom/stable -s build_type=Debug -o qt:qttools=True

      - name: Upload
        run: conan upload qt/5.15.0@vectrom/stable -r vectrom --all

  Mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install and configure Conan
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        run: |
          python -m pip install conan
          conan remote add vectrom https://artifactory.plociennik.net/artifactory/api/conan/conan
          conan user -p "$ARTIFACTORY_API_KEY" -r vectrom github

      - name: Create packages
        run: |
          conan create . qt/5.15.0@vectrom/stable -s build_type=Release -o qt:qttools=True
          conan create . qt/5.15.0@vectrom/stable -s build_type=Debug -o qt:qttools=True

      - name: Upload
        run: conan upload qt/5.15.0@vectrom/stable -r vectrom --all
